[package]
name = "zebratron-tools"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
image = "0.24"
hound = "3.5"

[[bin]]
name = "png_to_sprite"
path = "src/png_to_sprite.rs"

[[bin]]
name = "wav_to_sample"
path = "src/wav_to_sample.rs"